dimensions utility

diff --git a/Assignment 1/stats b/Assignment 1/stats
--- a/Assignment 1/stats
+++ b/Assignment 1/stats
@@ -8,29 +8,47 @@ declare -i COL=0;
 checkValidFile()
 {
     if [ ! -f $FILE ]; then
-        echo "./stats: cannot read $FILE";
-        exit;
+        echo "$0 cannot read $FILE";
+        exit 1;
     fi
+}
+
+DimensionsUtil()
+{
+    ROW=$(cut -f 1 $FILE | wc -l);
+    COL=$(head -n 1 $FILE | tr '\t' '\n' | wc -l);
+
+    echo "ROW: $ROW";
+    echo "COL: $COL";
 }
 
 FillFileRow()
 {
     while read line; 
     do
-        echo $( for i in $line; do echo -e "$i\t";done | sort -n ) #>> $TEMPFILE
+        echo $( for i in $line; do echo -e "$i\t";done | sort -n ) | tr ' ' '\t' #>> $TEMPFILE
     done < $FILE;
 }
 
 FillFileCol()
 {
- echo fuck;
+    echo "fuck";
+}
+
+Cleanup()
+{
+    rm $TEMPFILE;
 }
 
 rows_func() 
 {
     checkValidFile;
-
+    DimensionsUtil;
+    
     FillFileRow;
+    
+
+    echo -e "Average\tMedian";
 
 
 }
@@ -38,7 +56,8 @@ rows_func()
 cols_func()
 {
     checkValidFile; 
-    
+    DimensionsUtil;
+
     FillFileCol;
 
     #Averages logic
